### ISSUE TITLE
How to patch the dsdt for sleep and wake?

### ISSUE THREAD

**Issue by jardenliu** [badruzeus/EFI-Asus-A43SJ#1]
Hi,
   I have  a ASUS laptop (F450VC I5-3230) too. However, after I installed high sierra 10.13.6 and patched the DSDT for the battery, audio, graphics and so on, then they worked. But `sleep and wake` is not working, It look like no sleep,the  screen was extinguished, the fan still working.
  Could you please tell me how to patch the dsdt for sleep and wake?

**Comment by badruzeus** [comment]
Hi, we have different mach. But take a look for guides here. Thanks.
https://www.insanelymac.com/forum/topic/306737-a-guide-on-fixing-sleep-issues/

**Comment by jardenliu** [comment]
I fixed it. thanks
